### PR TITLE
add example 4

### PR DESCRIPTION
**Pull request by robsonpeixoto**

### CODE REVIEW

**Comment by robsonpeixoto** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example-4 will be created
+ resource "null_resource" "example-4" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://d2ba5b9840d8.ngrok.io/lock?id=robsonpeixoto%252Fterraform-github-provider-study%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by robsonpeixoto** [comment]
atlantis apply

**Comment by robsonpeixoto** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
null_resource.example-4: Creating...
null_resource.example-4: Creation complete after 0s [id=1086091967546241544]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by robsonpeixoto** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by robsonpeixoto** [comment]
Automerging failed:
```
merging pull request: PUT https://api.github.com/repos/robsonpeixoto/terraform-github-provider-study/pulls/4/merge: 405 Pull Request is not mergeable []
```

**Comment by robsonpeixoto** [comment]
atlantis apply

**Comment by robsonpeixoto** [comment]
Ran Apply for 0 projects:

**Review by rgcs88 — APPROVED** [review]

**Comment by robsonpeixoto** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # null_resource.example will be created
+ resource "null_resource" "example" {
      + id = (known after apply)
    }

  # null_resource.example-3 will be created
+ resource "null_resource" "example-3" {
      + id = (known after apply)
    }

  # null_resource.example-4 will be created
+ resource "null_resource" "example-4" {
      + id = (known after apply)
    }

  # null_resource.example2 will be created
+ resource "null_resource" "example2" {
      + id = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://d2ba5b9840d8.ngrok.io/lock?id=robsonpeixoto%252Fterraform-github-provider-study%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 4 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by robsonpeixoto** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
